services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    ports:
      - "5100:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /Users/mac/IdeaProjects/patient-management-volumes/patient-service-db:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "8100:8100"
    environment:
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: "9200"
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal
    depends_on:
      - patient-service-db

  billing-service-db:
    image: postgres:latest
    container_name: billing-service-db
    ports:
      - "5200:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /Users/mac/IdeaProjects/patient-management-volumes/billing-service-db:/var/lib/postgresql/data
    networks:
      - internal

  billing-service:
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "8200:8200"
      - "9200:9200"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://billing-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      TREATMENT_SERVICE_ADDRESS: treatment-service
      TREATMENT_SERVICE_GRPC_PORT: "9500"
    depends_on:
      - billing-service-db
      - treatment-service
    networks:
      - internal

  treatment-service-db:
    image: mongo:latest
    container_name: treatment-service-db
    ports:
      - "5300:27017"
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - /Users/mac/IdeaProjects/patient-management-volumes/treatment-service-db:/var/lib/mongodb/data
    networks:
      - internal

  treatment-service:
    image: treatment-service:latest
    container_name: treatment-service
    ports:
      - "8500:8500"
      - "9500:9500"
    environment:
      SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
      SPRING_DATA_MONGODB_DATABASE: db
      SPRING_DATA_MONGODB_HOST: treatment-service-db
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: root
    networks:
      - internal
    depends_on:
      - treatment-service-db

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
    networks:
      - internal

  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    ports:
      - "8300:8300"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - internal
    depends_on:
      - kafka

networks:
  internal:
    driver: bridge
