name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_HUB_REPOSITORY: svidak/patient-management-system
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Patient Service
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:patient-service-latest ./patient-service
          docker push $DOCKER_HUB_REPOSITORY:patient-service-latest

      - name: Build and push Billing Service
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:billing-service-latest ./billing-service
          docker push $DOCKER_HUB_REPOSITORY:billing-service-latest

      - name: Build and push Treatment Service
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:treatment-service-latest ./treatment-service
          docker push $DOCKER_HUB_REPOSITORY:treatment-service-latest

      - name: Build and push Analytics Service
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:analytics-service-latest ./analytics-service
          docker push $DOCKER_HUB_REPOSITORY:analytics-service-latest
