name: Build and Push Docker Images

on:
  push:
    branches: [ "billing-service-crud" ]
    paths:
      - 'patient-service/**'
      - 'billing-service/**'
      - 'treatment-service/**'
      - 'analytics-service/**'

env:
  DOCKER_HUB_REPOSITORY: svidak/patient-management-system
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Patient Service
        if: contains(github.event.commits[0].modified, 'patient-service/')
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:patient-service-$GITHUB_SHA ./patient-service
          docker push $DOCKER_HUB_REPOSITORY:patient-service-$GITHUB_SHA
          docker tag $DOCKER_HUB_REPOSITORY:patient-service-$GITHUB_SHA $DOCKER_HUB_REPOSITORY:patient-service-latest
          docker push $DOCKER_HUB_REPOSITORY:patient-service-latest

      - name: Build and push Billing Service
        if: contains(github.event.commits[0].modified, 'billing-service/')
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:billing-service-$GITHUB_SHA ./billing-service
          docker push $DOCKER_HUB_REPOSITORY:billing-service-$GITHUB_SHA
          docker tag $DOCKER_HUB_REPOSITORY:billing-service-$GITHUB_SHA $DOCKER_HUB_REPOSITORY:billing-service-latest
          docker push $DOCKER_HUB_REPOSITORY:billing-service-latest

      - name: Build and push Treatment Service
        if: contains(github.event.commits[0].modified, 'treatment-service/')
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:treatment-service-$GITHUB_SHA ./treatment-service
          docker push $DOCKER_HUB_REPOSITORY:treatment-service-$GITHUB_SHA
          docker tag $DOCKER_HUB_REPOSITORY:treatment-service-$GITHUB_SHA $DOCKER_HUB_REPOSITORY:treatment-service-latest
          docker push $DOCKER_HUB_REPOSITORY:treatment-service-latest

      - name: Build and push Analytics Service
        if: contains(github.event.commits[0].modified, 'analytics-service/')
        run: |
          docker build -t $DOCKER_HUB_REPOSITORY:analytics-service-$GITHUB_SHA ./analytics-service
          docker push $DOCKER_HUB_REPOSITORY:analytics-service-$GITHUB_SHA
          docker tag $DOCKER_HUB_REPOSITORY:analytics-service-$GITHUB_SHA $DOCKER_HUB_REPOSITORY:analytics-service-latest
          docker push $DOCKER_HUB_REPOSITORY:analytics-service-latest
